//! Native real-source witness. Fixture output is generated by NQ-ng's local
//! diagnostic/store qualification test, not by a classic binary or a stub.
use nightshiftd::nq_disposition::{
    derive_disposition, Disposition, NqRelianceReceiptDto, SourceState,
};

#[test]
fn current_parser_rejects_classic_schema() {
    let bytes = include_bytes!("fixtures/nq_reliance/valid_operational_health_reliance.json");
    assert!(NqRelianceReceiptDto::parse_checked(bytes, "nightshift-readonly").is_err());
}

#[test]
#[ignore = "requires NQ_PURPOSE_FIXTURE_OUTPUT from native locally qualified store test"]
fn real_native_historical_scope_and_binding_controls() {
    let root = std::path::PathBuf::from(std::env::var("NQ_PURPOSE_FIXTURE_OUTPUT").unwrap());
    let bytes = std::fs::read(root.join("historical-support.json")).unwrap();
    let request: serde_json::Value =
        serde_json::from_slice(&std::fs::read(root.join("request.json")).unwrap()).unwrap();
    let at = request["evaluated_at"].as_str().unwrap();
    let receipt = NqRelianceReceiptDto::parse_for_request(&bytes, &request, at).unwrap();
    let disposition = derive_disposition(
        &SourceState::Fresh,
        Some(&receipt),
        at,
        "nightshift-readonly",
    );
    assert_eq!(disposition.disposition, Disposition::ContinueObserving);
    assert!(receipt
        .does_not_establish
        .iter()
        .any(|s| s.contains("source-world currentness")));
    for field in ["purpose", "claim", "subject_digest", "consumer"] {
        let mut wrong = request.clone();
        wrong[field] = serde_json::json!("different");
        assert!(NqRelianceReceiptDto::parse_for_request(&bytes, &wrong, at).is_err());
    }
    let value: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
    assert!(NqRelianceReceiptDto::parse_for_request(
        &bytes,
        &request,
        value["expires_at"].as_str().unwrap()
    )
    .is_err());
    let mut changed = value;
    changed["decision"] = serde_json::json!("authorized_reliance");
    assert!(NqRelianceReceiptDto::parse_for_request(
        &serde_json::to_vec(&changed).unwrap(),
        &request,
        at
    )
    .is_err());
    let current_bytes = std::fs::read(root.join("current-support.json")).unwrap();
    let current: serde_json::Value = serde_json::from_slice(&current_bytes).unwrap();
    let current_dto =
        NqRelianceReceiptDto::parse_for_request(&current_bytes, &current["request"], at).unwrap();
    assert_eq!(
        derive_disposition(
            &SourceState::Fresh,
            Some(&current_dto),
            at,
            "nightshift-readonly"
        )
        .disposition,
        Disposition::HumanJudgmentRequired
    );
}
